### ISSUE TITLE
Crash on Android vulkan caused by GPU resource dead lock

### ISSUE THREAD

**Issue by TsinStudio** [TsinStudio/kaleido3d#30]
> 08-09 10:22:02.000 1345-1396/com.tsinstudio.triangle W/Adreno-GSL: <gsl_ldd_control:477>: ioctl fd 40 code 0xc038093d (IOCTL_KGSL_SUBMIT_COMMANDS) failed: errno 35 Resource deadlock would occur
> 08-09 10:22:02.000 1345-1396/com.tsinstudio.triangle W/Adreno-GSL: <log_gpu_snapshot:386>: panel.gpuSnapshotPath is not set.not generating user snapshot

**Comment by 26prajval98** [comment]
Hi could you tell me the reason which gave you this error ?

**Comment by DsoTsin** [comment]
> Hi could you tell me the reason which gave you this error ?

I'm afraid that I had forgotten the reason..

**Comment by 26prajval98** [comment]
Oh, thanks for replying. If I get the fix I'll put it in here. Also if you remember the fix please do leave a comment here. It would be greatly helpful to me and the Vulkan community.

**Comment by 26prajval98** [comment]
I fixed this issue. It was happening because the android native window was not free and my device was trying to submit the queue. Hence leading to a deadlock.

**Comment by leeqiaogithub** [comment]
> I fixed this issue. It was happening because the android native window was not free and my device was trying to submit the queue. Hence leading to a deadlock.

hello.I wonder how to solve this problem.thanks

**Comment by OpenSauce04** [comment]
The lack of information in this thread despite two different people finding the solution and choosing not to share any useful information sucks, I am currently attempting to fix this exact issue 🙃
